"""Add image url to comment

Revision ID: 30671f73cac4
Revises: 8ecceef3d2c3
Create Date: 2025-06-26 10:09:09.587445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30671f73cac4'
down_revision: Union[str, None] = '8ecceef3d2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'image_url')
    # ### end Alembic commands ###
