"""Update Comment to save image_key

Revision ID: 3a24235b6ba8
Revises: f9cfce09827d
Create Date: 2025-06-30 14:34:27.973365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a24235b6ba8'
down_revision: Union[str, None] = 'f9cfce09827d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
