"""Set image_url as optional in schema

Revision ID: 62f6a7f02648
Revises: 76f46e8fb796
Create Date: 2025-06-26 11:48:58.012479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62f6a7f02648'
down_revision: Union[str, None] = '76f46e8fb796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
